### ISSUE TITLE
Add properties parameter to grid5000_job resource

### ISSUE THREAD

**Issue by Nivekiba** [pmorillon/terraform-provider-grid5000#6]
Hello @pmorillon 
i'm back to ask you how to use additional options in grid5000 while deploying using terraform

i would like to integrate the **-p** option of the **oarsub** command in my terraform deployment script

It's possible ?if yes how ?

**Comment by pmorillon** [comment]
Hello,

Instead of `oarsub -p "cluster='parasilo'" -l /nodes=1,walltime=2` i prefer to use `oarsub -l {"cluster='parasilo'"}/nodes=1,walltime=2`, especially when you ask for multiple kind of resources : 

```sh
oarsub -t deploy -l {"type='kavlan-local'"}/vlan=1+{"cluster='paravance'"}/nodes=3 -I
```

with the API, notation is quite different :  `resources = "{cluster='parasilo'}/nodes=1,walltime"`

But if you really want to use the property field i can add it, i think it's possible through the OAR API, see [POST /jobs](http://oar.imag.fr/docs/latest/user/api.html#post-jobs)

**Comment by Nivekiba** [comment]
And the **-t** option ?

**Comment by Nivekiba** [comment]
And it is possible to change the default partition where the OS is installed ?

in command line we use **-p** option of the **kadeploy3*
in terraform plugin of grid5k is there an attribute ?

**Comment by pmorillon** [comment]
02612df7c868f9aad3ebebe9f364b802d2e12115

**Comment by Nivekiba** [comment]
I was talking about grid5000DeploymentFields... In the case i want to deploy environment (ubuntu for example) using kadeploy but change the default partition where the system is install
